### ISSUE TITLE
Handle h265 on Local Recordings

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-server#817] opened 2017-10-11 09:46 UTC
Either by giving an error message or (better) by making it work.

**Comment by marcoherbst** [comment] 2018-02-12 10:47
https://github.com/evercam/evercam-server/issues/779

**Comment by marcoherbst** [comment] 2018-04-23 10:52
@azharmalik3 maybe ffmpeg 4.0 impacts this.

**Comment by marcoherbst** [comment] 2018-05-03 08:00
Closing this. Duplicate of 779.

**Closed by marcoherbst** 2018-05-03 08:00 UTC
