### ISSUE TITLE
Calendar shows recordings, but none visible...

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#524] opened 2016-11-02 15:15 UTC
https://dash.evercam.io/v1/cameras/glendruid2/recordings/snapshots/2016-10-19T17:00:02.000Z

What I see: 19th October ... see 18:00 ... blue, but no jpegs

**Comment by ijunaid8088** [comment] 2016-11-30 09:48
There is no quick fix to this issue. So Am moving this to future milestone for now.

**Comment by ijunaid8088** [comment] 2017-02-01 09:56
For the follow-up:

This issue coming due to one hour of daylight saving in Dublin after October.

The issue is only present before November and after onwards everything is fine.

**Comment by ijunaid8088** [comment] 2017-02-02 07:17
This issue is fixed now. 

In past, we were not using proper methods to shift timezone. Instead of using `shift_zone', timestamp was being created with `offset` values which were not covering DST values. 

It is fixed in https://github.com/evercam/evercam-server/pull/629 and now working fine.

**Closed by ijunaid8088** 2017-02-02 07:17 UTC
Labels: in progress
